from fastapi import FastAPI, Depends, HTTPException, status
from sqlalchemy.orm import Session
from sqlalchemy import text
from database import get_db, engine
import models
import schemas
from typing import List

app = FastAPI()


@app.get("/db-check")
def check_db_connection(db: Session = Depends(get_db)):
    try:
        # Attempt a simple query to verify the connection
        db.execute(text("SELECT 1"))
        return {"status": "database is connected"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Database connection failed: {str(e)}")
    

models.Base.metadata.create_all(bind=engine)

@app.get("/")
def read_root():
    return "Task Manager API running"

@app.get("/health")
def health_check():
    return {"status": "ok"}

@app.post("/tasks", response_model=schemas.TaskResponse, status_code=status.HTTP_201_CREATED)
def create_task(task: schemas.TaskCreate, db: Session = Depends(get_db)):
    new_task = models.Task(**task.model_dump()) 
    db.add(new_task)
    
    db.commit()
    
    # Refresh the object to get the ID and created_at generated by Postgres
    db.refresh(new_task)
    
    return new_task

@app.get("/tasks", response_model=List[schemas.TaskResponse])
def get_tasks(db: Session = Depends(get_db)):
    tasks = db.query(models.Task).all()
    return tasks

@app.get("/tasks/{id}", response_model=schemas.TaskResponse)
def get_task(id: int, db: Session = Depends(get_db)):
    # Query the database for a task with the matching ID
    task = db.query(models.Task).filter(models.Task.id == id).first()
    if not task:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail=f"Task with id {id} not found"
        )
    return task

@app.put("/tasks/{id}", response_model=schemas.TaskResponse)
def update_task(id: int, task_update: schemas.TaskCreate, db: Session = Depends(get_db)):
    task = db.query(models.Task).filter(models.Task.id == id).first()
    if not task:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail=f"Task with id {id} not found"
        )
    
    task.title = task_update.title
    task.completed = task_update.completed
    
    db.commit()
    db.refresh(task)
    
    return task


@app.delete("/tasks/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_task(id: int, db: Session = Depends(get_db)):
    task = db.query(models.Task).filter(models.Task.id == id).first()
    if not task:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, 
            detail=f"Task with id {id} not found"
        )
    
    db.delete(task)
    db.commit()
    
    return None  